#tag::micronaut[]
micronaut:
  application:
    name: email-service
  server:
    port: 8090
#end::micronaut[]

#tag::zipkin[]
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1 # <1>
#end::zipkin[]

#tag::email[]
email:
  host: smtp.gmail.com
  port: 587
  username: <prod-email>
  password: <prod-key>
  protocol: smtp
  auth: true
  starttls:
    enable: true
  debug: true
#end::email[]
